package day11;

public class ExceptionExam1 {
    public static void main(String[] args) {
        int[] iarr = {1, 2, 3, 4};
        System.out.println(iarr[4]); // 여기서 예외 발생하고 프로그램이 종료됨

        System.out.println("다음 해야 할 일1");
        System.out.println("다음 해야 할 일2");
        System.out.println("다음 해야 할 일3");
        System.out.println("프로그램 종료.");
    }
}
